version: "3.8"

services:
  easydb-backend:
    image: shencangsheng/easydb-backend:v0.3.0
    restart: always
    environment:
      TZ: Asia/Shanghai
    networks:
      - easydb-net
    volumes:
      - db-data:/usr/local/app/sqlite
      - "./example:/var/lib/easydb/example"
  easydb-frontend:
    image: shencangsheng/easydb-frontend:v0.3.0
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8088:80"
    networks:
      - easydb-net
volumes:
  db-data:
networks:
  easydb-net: